version: '3.8'

# Production overrides for docker-compose.yml
services:
  # MongoDB Database - Production settings
  mongodb:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Payload CMS Backend - Production settings
  payload:
    build:
      context: ./src/payload
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    restart: always
    volumes:
      # In production, we don't mount the source code
      - payload_media:/app/media
    environment:
      - NODE_ENV=production
      - DEBUG=false
      - PAYLOAD_SEED=false
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Next.js Frontend - Production settings
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    restart: always
    # In production, we don't mount the source code
    volumes: []
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis - Production settings
  redis:
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"